name: todo_ddc
description: Sample TODO app with polymer2+DDC
version: 0.0.1
dependencies:
 logging: any
 todo_main:
   path: todo_main
 polymer_element: "^2.0.2"
 polymerize: ^0.9.1+1

# polymer_elements:
#  git:
#    url: https://github.com/dam0vm3nt/polymerize_elements.git
#    ref: v0.1.0
# polymer_element: 
#   path: ../polymer_element

web:
 compiler:
  release: dartdevc
  debug: dartdevc

dependency_overrides:
# polymer_element:
#  path: ../polymer_element
# polymerize_common:
#  path: ../polymerize_common
# polymer_elements:
#  path: /home/vittorio/Develop/dart/polymer_elements
# html5:
#  path: ../html_lib
 polymer_elements:
#  path: ../polymer_elements
  git:
    url: https://github.com/polymer-dart/polymerize_elements.git
    ref: v0.4.1
# js:
#  path: /home/vittorio/.pub-cache/hosted/pub.dartlang.org/js-0.6.1
# polymerize:
#   path: ../polymerize
dev_dependencies:
#  polymerize: ^0.8.5

transformers:
 - polymerize:
    entry-point: lib/index.dart
